import { Container, Grid } from '@mui/material'
import Head from 'next/head'
import LoginForm from '../../components/templates/LoginForm'

export default function Home() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <Grid container justifyContent="center" alignItems="center" sx={{ height: '100vh' }}>
                    <Grid item xs={4}>
                        <LoginForm />
                    </Grid>
                </Grid>
            </Container>
        </>
    )
}
