import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

type Data = {
  name: string
  email: string
  address: string
}

const api = async () => {
  const response = await fetch('http://localhost:8081/api/data');
  const res: Data = await response.json();
  return res;
}

export default function Dashboard() {
  const [data, setData] = useState<Data>({
    name: '',
    email: '',
    address: '',
  });

  const handle = async () => {
    const res = await api();
    setData(res);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          This is dashboard.
        </div>
        <div>
          {data.name}
        </div>
        <button onClick={handle}>画像を検索</button>
      </main>

    </div>
  )
}
